

version: '2'

services:

  orderer.wabco.com:
    container_name: orderer.wabco.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/wabco.com/orderers/orderer.wabco.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/wabco.com/orderers/orderer.wabco.com/tls/:/var/hyperledger/orderer/tls
    - orderer.wabco.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.wabco.com:
    container_name: peer0.wabco.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.wabco.com
      - CORE_PEER_ADDRESS=peer0.wabco.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.wabco.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.wabco.com:7051
      - CORE_PEER_LOCALMSPID=WabcoMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/wabco.com/peers/peer0.wabco.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/wabco.com/peers/peer0.wabco.com/tls:/etc/hyperledger/fabric/tls
        - peer0.wabco.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.tms.com:
    container_name: peer0.tms.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.tms.com
      - CORE_PEER_ADDRESS=peer0.tms.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tms.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tms.com:7051
      - CORE_PEER_LOCALMSPID=TmsMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/tms.com/peers/peer0.tms.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/tms.com/peers/peer0.tms.com/tls:/etc/hyperledger/fabric/tls
        - peer0.tms.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053